### PR TITLE
Add ldc to the supported compilers

### LINKED ISSUE #75: Support LDC?
Hi, 
I found this useful for small experiment.
However, as drepl utilizes dmd to evaluate expressions, I cannot use on my ARM box.
Are there any plans to support ldc? 

Thanks.

### PR DESCRIPTION
**Pull request by ljmf00**
This PR will add support for LDC compiler. I'm not quite sure if it's better to refactor DMD Engine to be widely supported for every D compiler. Currently `ldmd` supports arguments of `dmd` using `ldc`.

Fixes #75 .

### CODE REVIEW

**Comment by ljmf00** [comment]
@MartinNowak can you take a look at this? I'm not sure if the library name is the same across all systems, but I supposed.

**Review by MartinNowak — APPROVED** [review]
Looks about right, think the dmd interfaces are fine.

**Comment by ljmf00** [comment]
> Looks about right, think the dmd interfaces are fine.

Would be cool to add more tests with at least one more linux distro to differ the environment. I'm saying that because I had issues with compiler passed to `DMD` environment variable. In archlinux `ldmd` is actually symbolic linked to `ldmd2`.

**Comment by ljmf00** [comment]
Rebased with `master`

**Comment by ljmf00** [comment]
> Looks about right, think the dmd interfaces are fine.

@MartinNowak did you forgot to merge? I already rebased with `master`.

**Pull request merged**
